trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_WORKING_DIR: '$(System.DefaultWorkingDirectory)'

stages:
- stage: Validate
  jobs:
  - job: validate
    displayName: 'Terraform Validate'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - task: TerraformCLI@0
      inputs:
        command: 'init'
        workingDirectory: '$(TF_WORKING_DIR)'
        backendType: 'azurerm'
        backendServiceArm: 'SCN-TFM-HUB'

    - task: TerraformCLI@0
      inputs:
        command: 'validate'
        workingDirectory: '$(TF_WORKING_DIR)'

- stage: Plan
  jobs:
  - job: plan
    displayName: 'Terraform Plan'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        workingDirectory: '$(TF_WORKING_DIR)'
        environmentServiceNameAzureRM: 'SCN-TFM-HUB'

- stage: Apply
  jobs:
  - job: apply
    displayName: 'Terraform Apply'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'hub-default'
    steps:
    - task: TerraformCLI@0
      inputs:
        command: 'apply'
        workingDirectory: '$(TF_WORKING_DIR)'
        environmentServiceNameAzureRM: 'SCN-TFM-HUB'
        commandOptions: '-auto-approve'

- stage: Drift
  jobs:
  - job: drift
    displayName: 'Terraform Drift Detection'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        workingDirectory: '$(TF_WORKING_DIR)'
        environmentServiceNameAzureRM: 'SCN-TFM-HUB'
        commandOptions: '-detailed-exitcode'
